.class public final Lhf/j;
.super Lhf/l;
.source "SourceFile"

# interfaces
.implements Lef/c;


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lhf/j$a;
    }
.end annotation

.annotation system Ldalvik/annotation/Signature;
    value = {
        "<T:",
        "Ljava/lang/Object;",
        ">",
        "Lhf/l;",
        "Lef/c<",
        "TT;>;"
    }
.end annotation


# instance fields
.field private final e:Lhf/c0$b;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Lhf/c0$b<",
            "Lhf/j<",
            "TT;>.a;>;"
        }
    .end annotation
.end field

.field private final f:Ljava/lang/Class;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/lang/Class<",
            "TT;>;"
        }
    .end annotation
.end field


# direct methods
.method public constructor <init>(Ljava/lang/Class;)V
    .locals 1
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Ljava/lang/Class<",
            "TT;>;)V"
        }
    .end annotation

    const-string v0, "jClass"

    invoke-static {p1, v0}, Lkotlin/jvm/internal/m;->g(Ljava/lang/Object;Ljava/lang/String;)V

    invoke-direct {p0}, Lhf/l;-><init>()V

    iput-object p1, p0, Lhf/j;->f:Ljava/lang/Class;

    new-instance p1, Lhf/j$b;

    invoke-direct {p1, p0}, Lhf/j$b;-><init>(Lhf/j;)V

    invoke-static {p1}, Lhf/c0;->a(Lxe/a;)Lhf/c0$b;

    move-result-object p1

    iput-object p1, p0, Lhf/j;->e:Lhf/c0$b;

    return-void
.end method

.method public static final synthetic C(Lhf/j;)Lig/a;
    .locals 0

    invoke-direct {p0}, Lhf/j;->E()Lig/a;

    move-result-object p0

    return-object p0
.end method

.method public static final synthetic D(Lhf/j;)Ljava/lang/Void;
    .locals 0

    invoke-direct {p0}, Lhf/j;->J()Ljava/lang/Void;

    move-result-object p0

    return-object p0
.end method

.method private final E()Lig/a;
    .locals 2

    sget-object v0, Lhf/g0;->b:Lhf/g0;

    invoke-virtual {p0}, Lhf/j;->a()Ljava/lang/Class;

    move-result-object v1

    invoke-virtual {v0, v1}, Lhf/g0;->b(Ljava/lang/Class;)Lig/a;

    move-result-object v0

    return-object v0
.end method

.method private final J()Ljava/lang/Void;
    .locals 4

    sget-object v0, Lif/e;->c:Lif/e$a;

    invoke-virtual {p0}, Lhf/j;->a()Ljava/lang/Class;

    move-result-object v1

    invoke-virtual {v0, v1}, Lif/e$a;->a(Ljava/lang/Class;)Lif/e;

    move-result-object v0

    if-eqz v0, :cond_0

    invoke-virtual {v0}, Lif/e;->e()Lcg/a;

    move-result-object v0

    if-eqz v0, :cond_0

    invoke-virtual {v0}, Lcg/a;->c()Lcg/a$a;

    move-result-object v0

    goto :goto_0

    :cond_0
    const/4 v0, 0x0

    :goto_0
    if-eqz v0, :cond_1

    sget-object v1, Lhf/k;->a:[I

    invoke-virtual {v0}, Ljava/lang/Enum;->ordinal()I

    move-result v2

    aget v1, v1, v2

    packed-switch v1, :pswitch_data_0

    new-instance v0, Loe/p;

    invoke-direct {v0}, Loe/p;-><init>()V

    throw v0

    :pswitch_0
    new-instance v1, Lhf/a0;

    new-instance v2, Ljava/lang/StringBuilder;

    invoke-direct {v2}, Ljava/lang/StringBuilder;-><init>()V

    const-string v3, "Unknown class: "

    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {p0}, Lhf/j;->a()Ljava/lang/Class;

    move-result-object v3

    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    const-string v3, " (kind = "

    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {v2, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    const/16 v0, 0x29

    invoke-virtual {v2, v0}, Ljava/lang/StringBuilder;->append(C)Ljava/lang/StringBuilder;

    invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v0

    invoke-direct {v1, v0}, Lhf/a0;-><init>(Ljava/lang/String;)V

    throw v1

    :pswitch_1
    new-instance v0, Ljava/lang/UnsupportedOperationException;

    new-instance v1, Ljava/lang/StringBuilder;

    invoke-direct {v1}, Ljava/lang/StringBuilder;-><init>()V

    const-string v2, "This class is an internal synthetic class generated by the Kotlin compiler, such as an anonymous class for a lambda, a SAM wrapper, a callable reference, etc. It\'s not a Kotlin class or interface, so the reflection "

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    const-string v2, "library has no idea what declarations does it have. Please use Java reflection to inspect this class: "

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {p0}, Lhf/j;->a()Ljava/lang/Class;

    move-result-object v2

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v1

    invoke-direct {v0, v1}, Ljava/lang/UnsupportedOperationException;-><init>(Ljava/lang/String;)V

    throw v0

    :pswitch_2
    new-instance v0, Ljava/lang/UnsupportedOperationException;

    new-instance v1, Ljava/lang/StringBuilder;

    invoke-direct {v1}, Ljava/lang/StringBuilder;-><init>()V

    const-string v2, "Packages and file facades are not yet supported in Kotlin reflection. "

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    const-string v2, "Meanwhile please use Java reflection to inspect this class: "

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {p0}, Lhf/j;->a()Ljava/lang/Class;

    move-result-object v2

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v1

    invoke-direct {v0, v1}, Ljava/lang/UnsupportedOperationException;-><init>(Ljava/lang/String;)V

    throw v0

    :cond_1
    :pswitch_3
    new-instance v0, Lhf/a0;

    new-instance v1, Ljava/lang/StringBuilder;

    invoke-direct {v1}, Ljava/lang/StringBuilder;-><init>()V

    const-string v2, "Unresolved class: "

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {p0}, Lhf/j;->a()Ljava/lang/Class;

    move-result-object v2

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v1

    invoke-direct {v0, v1}, Lhf/a0;-><init>(Ljava/lang/String;)V

    throw v0

    :pswitch_data_0
    .packed-switch 0x1
        :pswitch_2
        :pswitch_2
        :pswitch_2
        :pswitch_1
        :pswitch_0
        :pswitch_3
    .end packed-switch
.end method


# virtual methods
.method public final F()Lhf/c0$b;
    .locals 1
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()",
            "Lhf/c0$b<",
            "Lhf/j<",
            "TT;>.a;>;"
        }
    .end annotation

    iget-object v0, p0, Lhf/j;->e:Lhf/c0$b;

    return-object v0
.end method

.method public G()Lmf/e;
    .locals 1

    iget-object v0, p0, Lhf/j;->e:Lhf/c0$b;

    invoke-virtual {v0}, Lhf/c0$b;->c()Ljava/lang/Object;

    move-result-object v0

    check-cast v0, Lhf/j$a;

    invoke-virtual {v0}, Lhf/j$a;->k()Lmf/e;

    move-result-object v0

    return-object v0
.end method

.method public final H()Lqg/h;
    .locals 1

    invoke-virtual {p0}, Lhf/j;->G()Lmf/e;

    move-result-object v0

    invoke-interface {v0}, Lmf/e;->k()Lxg/c0;

    move-result-object v0

    invoke-virtual {v0}, Lxg/v;->j()Lqg/h;

    move-result-object v0

    return-object v0
.end method

.method public final I()Lqg/h;
    .locals 2

    invoke-virtual {p0}, Lhf/j;->G()Lmf/e;

    move-result-object v0

    invoke-interface {v0}, Lmf/e;->b0()Lqg/h;

    move-result-object v0

    const-string v1, "descriptor.staticScope"

    invoke-static {v0, v1}, Lkotlin/jvm/internal/m;->b(Ljava/lang/Object;Ljava/lang/String;)V

    return-object v0
.end method

.method public a()Ljava/lang/Class;
    .locals 1
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()",
            "Ljava/lang/Class<",
            "TT;>;"
        }
    .end annotation

    iget-object v0, p0, Lhf/j;->f:Ljava/lang/Class;

    return-object v0
.end method

.method public c()Ljava/lang/String;
    .locals 1

    iget-object v0, p0, Lhf/j;->e:Lhf/c0$b;

    invoke-virtual {v0}, Lhf/c0$b;->c()Ljava/lang/Object;

    move-result-object v0

    check-cast v0, Lhf/j$a;

    invoke-virtual {v0}, Lhf/j$a;->n()Ljava/lang/String;

    move-result-object v0

    return-object v0
.end method

.method public d()Ljava/lang/String;
    .locals 1

    iget-object v0, p0, Lhf/j;->e:Lhf/c0$b;

    invoke-virtual {v0}, Lhf/c0$b;->c()Ljava/lang/Object;

    move-result-object v0

    check-cast v0, Lhf/j$a;

    invoke-virtual {v0}, Lhf/j$a;->o()Ljava/lang/String;

    move-result-object v0

    return-object v0
.end method

.method public equals(Ljava/lang/Object;)Z
    .locals 1

    instance-of v0, p1, Lhf/j;

    if-eqz v0, :cond_0

    invoke-static {p0}, Lwe/a;->c(Lef/c;)Ljava/lang/Class;

    move-result-object v0

    check-cast p1, Lef/c;

    invoke-static {p1}, Lwe/a;->c(Lef/c;)Ljava/lang/Class;

    move-result-object p1

    invoke-static {v0, p1}, Lkotlin/jvm/internal/m;->a(Ljava/lang/Object;Ljava/lang/Object;)Z

    move-result p1

    if-eqz p1, :cond_0

    const/4 p1, 0x1

    goto :goto_0

    :cond_0
    const/4 p1, 0x0

    :goto_0
    return p1
.end method

.method public hashCode()I
    .locals 1

    invoke-static {p0}, Lwe/a;->c(Lef/c;)Ljava/lang/Class;

    move-result-object v0

    invoke-virtual {v0}, Ljava/lang/Object;->hashCode()I

    move-result v0

    return v0
.end method

.method public q()Ljava/util/Collection;
    .locals 3
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()",
            "Ljava/util/Collection<",
            "Lmf/l;",
            ">;"
        }
    .end annotation

    invoke-virtual {p0}, Lhf/j;->G()Lmf/e;

    move-result-object v0

    invoke-interface {v0}, Lmf/e;->getKind()Lmf/f;

    move-result-object v1

    sget-object v2, Lmf/f;->c:Lmf/f;

    if-eq v1, v2, :cond_1

    invoke-interface {v0}, Lmf/e;->getKind()Lmf/f;

    move-result-object v1

    sget-object v2, Lmf/f;->g:Lmf/f;

    if-ne v1, v2, :cond_0

    goto :goto_0

    :cond_0
    invoke-interface {v0}, Lmf/e;->h()Ljava/util/Collection;

    move-result-object v0

    const-string v1, "descriptor.constructors"

    invoke-static {v0, v1}, Lkotlin/jvm/internal/m;->b(Ljava/lang/Object;Ljava/lang/String;)V

    return-object v0

    :cond_1
    :goto_0
    invoke-static {}, Lkotlin/collections/o;->f()Ljava/util/List;

    move-result-object v0

    return-object v0
.end method

.method public r(Lig/f;)Ljava/util/Collection;
    .locals 3
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Lig/f;",
            ")",
            "Ljava/util/Collection<",
            "Lmf/t;",
            ">;"
        }
    .end annotation

    const-string v0, "name"

    invoke-static {p1, v0}, Lkotlin/jvm/internal/m;->g(Ljava/lang/Object;Ljava/lang/String;)V

    invoke-virtual {p0}, Lhf/j;->H()Lqg/h;

    move-result-object v0

    sget-object v1, Lrf/d;->i:Lrf/d;

    invoke-interface {v0, p1, v1}, Lqg/h;->d(Lig/f;Lrf/b;)Ljava/util/Collection;

    move-result-object v0

    invoke-virtual {p0}, Lhf/j;->I()Lqg/h;

    move-result-object v2

    invoke-interface {v2, p1, v1}, Lqg/h;->d(Lig/f;Lrf/b;)Ljava/util/Collection;

    move-result-object p1

    invoke-static {v0, p1}, Lkotlin/collections/o;->l0(Ljava/util/Collection;Ljava/lang/Iterable;)Ljava/util/List;

    move-result-object p1

    return-object p1
.end method

.method public s(I)Lmf/i0;
    .locals 9

    invoke-virtual {p0}, Lhf/j;->a()Ljava/lang/Class;

    move-result-object v0

    invoke-virtual {v0}, Ljava/lang/Class;->getSimpleName()Ljava/lang/String;

    move-result-object v0

    const-string v1, "DefaultImpls"

    invoke-static {v0, v1}, Lkotlin/jvm/internal/m;->a(Ljava/lang/Object;Ljava/lang/Object;)Z

    move-result v0

    if-eqz v0, :cond_1

    invoke-virtual {p0}, Lhf/j;->a()Ljava/lang/Class;

    move-result-object v0

    invoke-virtual {v0}, Ljava/lang/Class;->getDeclaringClass()Ljava/lang/Class;

    move-result-object v0

    if-eqz v0, :cond_1

    invoke-virtual {v0}, Ljava/lang/Class;->isInterface()Z

    move-result v1

    if-eqz v1, :cond_1

    invoke-static {v0}, Lwe/a;->e(Ljava/lang/Class;)Lef/c;

    move-result-object v0

    if-eqz v0, :cond_0

    check-cast v0, Lhf/j;

    invoke-virtual {v0, p1}, Lhf/j;->s(I)Lmf/i0;

    move-result-object p1

    return-object p1

    :cond_0
    new-instance p1, Loe/y;

    const-string v0, "null cannot be cast to non-null type kotlin.reflect.jvm.internal.KClassImpl<*>"

    invoke-direct {p1, v0}, Loe/y;-><init>(Ljava/lang/String;)V

    throw p1

    :cond_1
    invoke-virtual {p0}, Lhf/j;->G()Lmf/e;

    move-result-object v0

    instance-of v1, v0, Lvg/e;

    const/4 v2, 0x0

    if-nez v1, :cond_2

    move-object v0, v2

    :cond_2
    check-cast v0, Lvg/e;

    if-eqz v0, :cond_3

    invoke-virtual {v0}, Lvg/e;->E0()Ldg/c;

    move-result-object v1

    sget-object v3, Lgg/d;->j:Ljg/i$f;

    const-string v4, "JvmProtoBuf.classLocalVariable"

    invoke-static {v3, v4}, Lkotlin/jvm/internal/m;->b(Ljava/lang/Object;Ljava/lang/String;)V

    invoke-static {v1, v3, p1}, Lfg/f;->b(Ljg/i$d;Ljg/i$f;I)Ljava/lang/Object;

    move-result-object p1

    move-object v4, p1

    check-cast v4, Ldg/n;

    if-eqz v4, :cond_3

    invoke-virtual {p0}, Lhf/j;->a()Ljava/lang/Class;

    move-result-object v3

    invoke-virtual {v0}, Lvg/e;->D0()Ltg/l;

    move-result-object p1

    invoke-virtual {p1}, Ltg/l;->g()Lfg/c;

    move-result-object v5

    invoke-virtual {v0}, Lvg/e;->D0()Ltg/l;

    move-result-object p1

    invoke-virtual {p1}, Ltg/l;->j()Lfg/h;

    move-result-object v6

    invoke-virtual {v0}, Lvg/e;->F0()Lfg/a;

    move-result-object v7

    sget-object v8, Lhf/j$c;->a:Lhf/j$c;

    invoke-static/range {v3 .. v8}, Lhf/j0;->d(Ljava/lang/Class;Ljg/q;Lfg/c;Lfg/h;Lfg/a;Lxe/p;)Lmf/a;

    move-result-object p1

    check-cast p1, Lmf/i0;

    move-object v2, p1

    :cond_3
    return-object v2
.end method

.method public toString()Ljava/lang/String;
    .locals 9

    new-instance v0, Ljava/lang/StringBuilder;

    invoke-direct {v0}, Ljava/lang/StringBuilder;-><init>()V

    const-string v1, "class "

    invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-direct {p0}, Lhf/j;->E()Lig/a;

    move-result-object v1

    invoke-virtual {v1}, Lig/a;->g()Lig/b;

    move-result-object v2

    const-string v3, "packageFqName"

    invoke-static {v2, v3}, Lkotlin/jvm/internal/m;->b(Ljava/lang/Object;Ljava/lang/String;)V

    invoke-virtual {v2}, Lig/b;->c()Z

    move-result v3

    if-eqz v3, :cond_0

    const-string v2, ""

    goto :goto_0

    :cond_0
    new-instance v3, Ljava/lang/StringBuilder;

    invoke-direct {v3}, Ljava/lang/StringBuilder;-><init>()V

    invoke-virtual {v2}, Lig/b;->a()Ljava/lang/String;

    move-result-object v2

    invoke-virtual {v3, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    const-string v2, "."

    invoke-virtual {v3, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {v3}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v2

    :goto_0
    invoke-virtual {v1}, Lig/a;->h()Lig/b;

    move-result-object v1

    invoke-virtual {v1}, Lig/b;->a()Ljava/lang/String;

    move-result-object v3

    const-string v1, "classId.relativeClassName.asString()"

    invoke-static {v3, v1}, Lkotlin/jvm/internal/m;->b(Ljava/lang/Object;Ljava/lang/String;)V

    const/16 v4, 0x2e

    const/16 v5, 0x24

    const/4 v6, 0x0

    const/4 v7, 0x4

    const/4 v8, 0x0

    invoke-static/range {v3 .. v8}, Ljh/m;->J(Ljava/lang/String;CCZILjava/lang/Object;)Ljava/lang/String;

    move-result-object v1

    new-instance v3, Ljava/lang/StringBuilder;

    invoke-direct {v3}, Ljava/lang/StringBuilder;-><init>()V

    invoke-virtual {v3, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {v3, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {v3}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v1

    invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v0

    return-object v0
.end method

.method public v(Lig/f;)Ljava/util/Collection;
    .locals 3
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Lig/f;",
            ")",
            "Ljava/util/Collection<",
            "Lmf/i0;",
            ">;"
        }
    .end annotation

    const-string v0, "name"

    invoke-static {p1, v0}, Lkotlin/jvm/internal/m;->g(Ljava/lang/Object;Ljava/lang/String;)V

    invoke-virtual {p0}, Lhf/j;->H()Lqg/h;

    move-result-object v0

    sget-object v1, Lrf/d;->i:Lrf/d;

    invoke-interface {v0, p1, v1}, Lqg/h;->b(Lig/f;Lrf/b;)Ljava/util/Collection;

    move-result-object v0

    invoke-virtual {p0}, Lhf/j;->I()Lqg/h;

    move-result-object v2

    invoke-interface {v2, p1, v1}, Lqg/h;->b(Lig/f;Lrf/b;)Ljava/util/Collection;

    move-result-object p1

    invoke-static {v0, p1}, Lkotlin/collections/o;->l0(Ljava/util/Collection;Ljava/lang/Iterable;)Ljava/util/List;

    move-result-object p1

    return-object p1
.end method
